# Generated by Django 4.0 on 2021-12-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Отдел'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужчина'), ('woman', 'Женщина')], max_length=10, verbose_name='Пол'),
        ),
    ]
