# Generated by Django 4.0 on 2021-12-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='programminglanguage',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программрования'},
        ),
    ]
